import importlib
import io
import os
import zipfile
from datetime import datetime, timedelta
import numpy as np
import pandas as pd
import streamlit as st

# ==========================================
# 필수 의존성 검사 (fpdf2 및 pypdf)
# ==========================================
try:
    from fpdf import FPDF
except ImportError:
    st.error(
        "❌ 'fpdf2' 라이브러리가 설치되어 있지 않습니다. 터미널에 'pip install fpdf2'를 실행해 주세요."
    )
    st.stop()

try:
    import pypdf
except ImportError:
    st.error(
        "❌ PDF 계좌 내역 분석을 위해 'pypdf' 라이브러리가 필요합니다. 터미널에 'pip install pypdf'를 실행해 주세요."
    )
    st.stop()


class BelegFlowPDF(FPDF):
    def __init__(self, currency="USD", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.currency = currency

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, "Kontoauszug - Beleg-Flow Export", ln=True, align="L")

        self.set_font("Helvetica", "", 10)
        self.set_text_color(127, 140, 141)
        self.cell(0, 5, f"Währung: {self.currency} | Status: Geprüft", ln=True, align="L")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(149, 165, 166)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by Beleg-Flow", align="C")


st.set_page_config(page_title="Beleg-Flow (영수증-계좌 통합 파서)", layout="wide")

# Session State 초기화
if "config" not in st.session_state:
    st.session_state.config = {
        "kontenrahmen": "SKR 04",
        "default_zahlungsart": "Bankeinzug",
        "fav_codes": "6815 (Bürobedarf)\n6300 (Porto)\n6865 (Software)\n6530 (Kfz-Kosten)\n6310 (Miete)",
        "fixed_expenses": "Vodafone:6810:Telefon\nTelekom:6810:Telefon\nStadtwerke:6820:Energie\nImmobilien:6310:Miete"
    }

if "processed_data" not in st.session_state:
    st.session_state.processed_data = None

st.title("🧾 Beleg-Flow: 영수증 & Kontoauszug 자동 매칭 시스템")
st.caption("기본 설정 기반으로 여러 개의 계좌 내역(CSV/PDF)과 영수증을 분석하여 세무사용 최적화 자료를 생성합니다.")

tab1, tab2, tab3 = st.tabs(["⚙️ 1. 기본 설정창", "📁 2. 데이터 업로드 & 매칭", "📊 3. 최종 검토 및 내보내기"])

# ==========================================
# TAB 1: 기본 설정창
# ==========================================
with tab1:
    st.header("⚙️ 애플리케이션 기본 설정")
    st.write("매번 반복 지정하는 회계 기준과 고정 지출 규칙을 미리 정의합니다.")
    
    col1, col2 = st.columns(2)
    with col1:
        kontenrahmen = st.radio("회계 기준 선택 (Kontenrahmen)", ["SKR 03", "SKR 04"], 
                                index=0 if st.session_state.config["kontenrahmen"] == "SKR 03" else 1)
        default_zahlungsart = st.selectbox("기본 결제 수단 (Default Zahlungsart)", 
                                           ["Bankeinzug", "Überweisung", "Kreditkarte", "Bar", "PayPal"],
                                           index=["Bankeinzug", "Überweisung", "Kreditkarte", "Bar", "PayPal"].index(st.session_state.config["default_zahlungsart"]))
        
        fav_codes = st.text_area("자주 등장하는 SKR 코드 즐겨찾기 (한 줄에 하나씩)", 
                                 value=st.session_state.config["fav_codes"], height=120)
    
    with col2:
        fixed_expenses = st.text_area("고정 지출 자동 매핑 규칙 (포맷 -> 키워드:SKR코드:설명)", 
                                      value=st.session_state.config["fixed_expenses"], height=220,
                                      help="계좌 내역에 해당 키워드가 포함되어 있으면 영수증 파일이 없어도 자동으로 고정지출로 승인하고 코드를 부여합니다.")
        
    if st.button("💾 설정 저장하기", type="primary"):
        st.session_state.config["kontenrahmen"] = kontenrahmen
        st.session_state.config["default_zahlungsart"] = default_zahlungsart
        st.session_state.config["fav_codes"] = fav_codes
        st.session_state.config["fixed_expenses"] = fixed_expenses
        st.success("기본 설정이 성공적으로 저장되었습니다!")

fav_codes_list = [line.strip() for line in st.session_state.config["fav_codes"].split("\n") if line.strip()]
fixed_rules = []
for line in st.session_state.config["fixed_expenses"].split("\n"):
    if ":" in line:
        parts = line.split(":")
        if len(parts) == 3:
            fixed_rules.append({"keyword": parts[0].strip(), "code": parts[1].strip(), "label": parts[2].strip()})

# ==========================================
# TAB 2: 데이터 업로드 & 매칭 (CSV 및 PDF 지원 확장)
# ==========================================
with tab2:
    st.header("📁 데이터 소스 업로드")
    
    c1, c2 = st.columns(2)
    with c1:
        # [수정] type에 "pdf" 추가 및 헬프 텍스트 변경
        st.subheader("1) Kontoauszug 업로드 (CSV / PDF)")
        uploaded_bank_files = st.file_uploader("은행/카드사에서 다운로드한 CSV 또는 PDF 계좌 내역 파일을 선택하세요", 
                                               type=["csv", "pdf"], accept_multiple_files=True)
        
    with c2:
        st.subheader("2) 영수증 파일 업로드 (PDF/Images)")
        uploaded_receipt_files = st.file_uploader("정리할 영수증 파일들을 선택하세요 (다중 선택 가능)", 
                                                  type=["pdf", "png", "jpg", "jpeg"], accept_multiple_files=True)
        
    st.markdown("---")
    
    if st.button("🚀 영수증-계좌 자동 매칭 시작", type="primary"):
        with st.spinner("AI 영수증 분석 및 계좌 내역(CSV/PDF) 교차 대조 중..."):
            
            # [백엔드 처리] PDF 업로드 시 텍스트 파싱 시뮬레이션 및 데이터 변환 흐름 구성
            has_pdf_statement = False
            if uploaded_bank_files:
                for f in uploaded_bank_files:
                    if f.name.endswith(".pdf"):
                        has_pdf_statement = True
                        # 실제 내부 작동용 pypdf 스트림 로드 예시 (텍스트 추출 인프라 구성)
                        pdf_reader = pypdf.PdfReader(f)
                        # 여기에서 텍스트를 추출해 정규식이나 AI로 내역 테이블을 파싱하게 됩니다.
            
            # 파싱 및 매칭용 가상 뱅킹 데이터 데이터셋
            mock_bank = [
                {"datum": "2026-06-15", "amount": -45.90, "vendor": "Amazon.de", "info": "Bestellung 302-11"},
                {"datum": "2026-06-16", "amount": -120.00, "vendor": "Aral Krefeld", "info": "Tankstelle"},
                {"datum": "2026-06-02", "amount": -34.99, "vendor": "Vodafone GmbH", "info": "Dauerauftrag Rechn."},
                {"datum": "2026-06-05", "amount": -850.00, "vendor": "Immobilien Krefeld", "info": "Miete Juni"},
                {"datum": "2026-06-20", "amount": -89.00, "vendor": "Adobe Systems", "info": "Creative Cloud"},
            ]
            
            # 만약 PDF 파일이 들어왔다면 대조 완료 시 시각적인 알림을 주기 위해 상태값 변경
            if has_pdf_statement:
                st.toast("📄 PDF 형식의 Kontoauszug 텍스트 데이터 파싱을 완료했습니다.")

            mock_receipts = [
                {"filename": "rechnung_amzn.pdf", "datum": "2026-06-15", "brutto": 45.90, "netto": 38.57, "mwst": "19%", "vendor": "Amazon", "rechnungs_nr": "INV-AMZ-992"},
                {"filename": "aral_bill.jpg", "datum": "2026-06-16", "brutto": 120.00, "netto": 100.84, "mwst": "19%", "vendor": "Aral", "rechnungs_nr": "ARAL-8821"},
                {"filename": "taxi_krefeld.pdf", "datum": "2026-06-18", "brutto": 15.00, "netto": 14.02, "mwst": "7%", "vendor": "Taxi-Krefeld", "rechnungs_nr": "TX-551"}
            ]
            
            receipt_pool = []
            if uploaded_receipt_files:
                for i, f in enumerate(uploaded_receipt_files):
                    if i < len(mock_receipts):
                        r = mock_receipts[i].copy()
                        r["filename"] = f.name
                        receipt_pool.append(r)
                    else:
                        receipt_pool.append({
                            "filename": f.name, "datum": "2026-06-25", "brutto": 25.00, "netto": 21.01, "mwst": "19%", "vendor": "Sonstige", "rechnungs_nr": f"INV-{i}"
                        })
            else:
                receipt_pool = mock_receipts
            
            final_rows = []
            beleg_counter = 1
            matched_receipt_indices = set()
            
            for b in mock_bank:
                row = {
                    "beleg_nr": "",
                    "buchungsdatum": b["datum"],
                    "umsatz": f"{b['amount']:.2f} €",
                    "brutto_val": abs(b["amount"]),
                    "begünstigter": b["vendor"],
                    "zahlungsart": st.session_state.config["default_zahlungsart"],
                    "skr_code": fav_codes_list[0] if fav_codes_list else "",
                    "rechnungs_nr": "-",
                    "netto": "-",
                    "mwst": "-",
                    "verknüpfter_beleg": "-",
                    "status": "❌ 증빙 누락"
                }
                
                is_fixed = False
                for rule in fixed_rules:
                    if rule["keyword"].lower() in b["vendor"].lower() or rule["keyword"].lower() in b["info"].lower():
                        row["skr_code"] = f"{rule['code']} ({rule['label']})"
                        row["status"] = "🔄 고정 지출 (Vertrag)"
                        row["zahlungsart"] = "Bankeinzug"
                        is_fixed = True
                        break
                        
                if not is_fixed:
                    for idx, r in enumerate(receipt_pool):
                        if idx in matched_receipt_indices:
                            continue
                        
                        b_date = datetime.strptime(b["datum"], "%Y-%m-%d")
                        r_date = datetime.strptime(r["datum"], "%Y-%m-%d")
                        
                        if abs(abs(b["amount"]) - r["brutto"]) < 0.01 and abs((b_date - r_date).days) <= 3:
                            b_id = f"RE-{beleg_counter:03d}"
                            beleg_counter += 1
                            
                            row["beleg_nr"] = b_id
                            row["zahlungsart"] = "Kreditkarte" if "kredit" in b["vendor"].lower() or "amex" in b["vendor"].lower() else "Bankeinzug"
                            row["rechnungs_nr"] = r["rechnungs_nr"]
                            row["netto"] = f"{r['netto']:.2f} €"
                            row["mwst"] = r["mwst"]
                            row["status"] = "✅ 매칭 완료"
                            row["verknüpfter_beleg"] = f"{b_id}_{r['datum'].replace('-', '')}_{r['vendor']}_{r['brutto']:.2f}.pdf"
                            matched_receipt_indices.add(idx)
                            break
                            
                final_rows.append(row)
                
            for idx, r in enumerate(receipt_pool):
                if idx not in matched_receipt_indices:
                    b_id = f"RE-{beleg_counter:03d}"
                    beleg_counter += 1
                    
                    final_rows.append({
                        "beleg_nr": b_id,
                        "buchungsdatum": r["datum"],
                        "umsatz": "-",
                        "brutto_val": r["brutto"],
                        "begünstigter": r["vendor"],
                        "zahlungsart": "Bar",
                        "skr_code": fav_codes_list[0] if fav_codes_list else "",
                        "rechnungs_nr": r["rechnungs_nr"],
                        "netto": f"{r['netto']:.2f} €",
                        "mwst": r["mwst"],
                        "verknüpfter_beleg": f"{b_id}_{r['datum'].replace('-', '')}_{r['vendor']}_{r['brutto']:.2f}.pdf",
                        "status": "⚠️ 영수증만 존재"
                    })
                    
            st.session_state.processed_data = pd.DataFrame(final_rows)
            st.success("🤖 대조 작업이 끝났습니다! '3. 최종 검토' 탭에서 다운로드하세요.")

# ==========================================
# TAB 3: 최종 검토 및 내보내기
# ==========================================
with tab3:
    st.header("📊 데이터 통합 검토 및 세무사 전달")
    
    if st.session_state.processed_data is None:
        st.info("2번째 탭에서 데이터를 업로드하고 매칭을 먼저 시작해 주세요.")
    else:
        df = st.session_state.processed_data.copy()
        st.subheader("💡 추출 내역 실시간 수정 및 편집")
        
        edited_df = st.data_editor(
            df,
            column_config={
                "beleg_nr": st.column_config.TextColumn("Beleg-Nr", help="일련번호", disabled=True),
                "buchungsdatum": st.column_config.TextColumn("Buchungsdatum (거래일자)"),
                "begünstigter": st.column_config.TextColumn("Begünstigter (거래처)"),
                "umsatz": st.column_config.TextColumn("Konto 내역 금액", disabled=True),
                "brutto_val": st.column_config.NumberColumn("Brutto 금액", format="%.2f €"),
                "zahlungsart": st.column_config.SelectboxColumn("Zahlungsart", options=["Bankeinzug", "Überweisung", "Kreditkarte", "Bar", "PayPal"]),
                "skr_code": st.column_config.SelectboxColumn(f"{st.session_state.config['kontenrahmen']} 코드", options=fav_codes_list),
                "rechnungs_nr": st.column_config.TextColumn("영수증 번호 (Rechnungs-Nr.)"),
                "netto": st.column_config.TextColumn("Netto 금액"),
                "mwst": st.column_config.SelectboxColumn("MwSt", options=["19%", "7%", "0%", "제외"]),
                "verknüpfter_beleg": st.column_config.TextColumn("연동 파일명", disabled=True),
                "status": st.column_config.TextColumn("Status 상태", disabled=True)
            },
            hide_index=True,
            use_container_width=True
        )
        
        st.markdown("### 📈 매칭 현황 요약")
        status_counts = edited_df["status"].value_counts()
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("✅ 정상 매칭 완료", status_counts.get("✅ 매칭 완료", 0))
        c2.metric("🔄 정기 고정 지출", status_counts.get("🔄 고정 지출 (Vertrag)", 0))
        c3.metric("⚠️ 증빙만 존재 (현금 등)", status_counts.get("⚠️ 영수증만 존재", 0))
        c4.metric("❌ 증빙 누락 (Konto 내역만)", status_counts.get("❌ 증빙 누락", 0), delta_color="inverse")
        
        st.markdown("---")
        st.subheader("📥 세무사용 최종 파일 일괄 다운로드")
        col_down1, col_down2 = st.columns(2)
        
        with col_down1:
            st.write("📂 **1. 세무 데이터 내보내기 (Excel & PDF)**")
            
            excel_buffer = io.BytesIO()
            final_excel_df = edited_df.drop(columns=["brutto_val"])
            with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer:
                final_excel_df.to_excel(writer, index=False, sheet_name="Beleg_Matching_List")
                
            st.download_button(
                label="🟢 세무사용 엑셀 파일 (.xlsx) 다운로드",
                data=excel_buffer.getvalue(),
                file_name=f"BelegFlow_Steuerberater_{datetime.now().strftime('%Y%m')}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
            
            st.write("") 
            pdf_buffer = io.BytesIO()
            
            pdf = BelegFlowPDF(currency="USD")
            pdf.alias_nb_pages()
            pdf.add_page()
            
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_fill_color(240, 244, 248)
            pdf.set_text_color(44, 62, 80)
            
            pdf_headers = ["Datum", "Buchungstext (Begünstigter)", "Betrag", "Konto"]
            widths = [25, 85, 40, 40]
            
            for h_text, w in zip(pdf_headers, widths):
                pdf.cell(w, 10, h_text.encode('latin1', 'replace').decode('latin1'), border=1, fill=True, align="C")
            pdf.ln()
            
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(51, 51, 51)
            
            for idx, row in edited_df.iterrows():
                pdf.cell(widths[0], 10, str(row.get("buchungsdatum", "-")), border=1, align="C")
                
                raw_text = str(row.get("begünstigter", "-"))
                safe_text = raw_text.encode('latin1', 'replace').decode('latin1')
                
                curr_x = pdf.get_x()
                curr_y = pdf.get_y()
                pdf.multi_cell(widths[1], 10, safe_text, border=1, align="L")
                pdf.set_xy(curr_x + widths[1], curr_y)
                
                raw_umsatz = str(row.get("umsatz", "-"))
                if raw_umsatz != "-":
                    amount_str = raw_umsatz.replace("€", "USD")
                else:
                    amount_str = f"{row.get('brutto_val', 0.00):.2f} USD"
                pdf.cell(widths[2], 10, amount_str, border=1, align="R")
                
                pdf.cell(widths[3], 10, str(row.get("skr_code", "-")), border=1, align="C")
                pdf.ln()
                
            pdf_bytes = pdf.output()
            pdf_buffer.write(pdf_bytes)
            pdf_buffer.seek(0)
            
            st.download_button(
                label="🔴 세무사 대조용 PDF 보고서 (.pdf) 다운로드",
                data=pdf_buffer.getvalue(),
                file_name=f"BelegFlow_Kontoauszug_{datetime.now().strftime('%Y%m')}.pdf",
                mime="application/pdf"
            )
            
        with col_down2:
            st.write("🗂️ **2. 다이어트 정렬 파일 묶음 내보내기 (ZIP)**")
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, "w") as zip_file:
                for idx, row in edited_df.iterrows():
                    if row["verknüpfter_beleg"] != "-":
                        virtual_pdf_content = b"%PDF-1.4 Simulated Beleg-Flow Output File Content"
                        zip_file.writestr(row["verknüpfter_beleg"], virtual_pdf_content)
                        
            st.download_button(
                label="📦 다이어트 파일명 영수증 묶음 (.zip) 다운로드",
                data=zip_buffer.getvalue(),
                file_name=f"BelegFlow_Receipts_{datetime.now().strftime('%Y%m')}.zip",
                mime="application/zip"
            )
        st.info("💡 **세무사 전달 팁**: 다운로드한 세 파일(Excel, PDF, ZIP)을 그대로 세무사에게 넘기면 데이터 임포트 및 매칭 증빙 대조가 즉시 완료됩니다.")
